default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  host: 0.0.0.0
  port: 33061
  username: root
  password: ROOT_PASSWORD

development:
  <<: *default
  database: tcp_dev

test:
  <<: *default
  database: tcp_test

# production:
#   <<: *default

